sudo: required
dist: trusty
script: make test
language: cpp
addons:
  apt:
    packages:
    - build-essential
    - libftdi-dev
    - llvm-3.6
    - gcc-4.8
    - git
    - python
    - python3
before_install:
  - sudo add-apt-repository -y ppa:saltmakrell/ppa
  - sudo apt-get -y update
  - sudo apt-get -y install yosys
  - git clone https://github.com/cliffordwolf/icestorm /tmp/icestorm
  - pushd /tmp/icestorm
  - make -j2 && sudo make install
  - popd
os: linux
compiler:
  - gcc
  - clang
branches:
  except:
    - dummy
